version: "3.7"

services:
  reverseproxy:
    build: ./udagram-reverseproxy
    restart: always
    ports:
      - "8080:8080"

  frontend:
    build: ./udagram-frontend
    ports:
      - "8100:80"
    restart: always
    depends_on:
      - app

  app:
    build: ./udagram-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - ./udagram-api/.env

  feed-service:
    build: ./udagram-feed-service
    ports:
        - "4000:4000"
    restart: always
    depends_on:
      - postgres
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - ./udagram-feed-service/.env

  postgres:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - ./udagram-api/.env
