apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
spec:
  selector:
    matchLabels:
      app: feed-service
  replicas: 1
  template:
    metadata:
      labels:
        app: feed-service

    spec:
      containers:
        - name: feed-service
          image: "joelcolucci/udagram-feed-service"
          ports:
            - name: http
              containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_DB
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_SECRET
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_PROFILE
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: URL