apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: "joelcolucci/udagram-frontend"
          ports:
            - name: http
              containerPort: 8100
          env:      
            - name: PORT
              value: "5000"